/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.CourseCatalog;
import Business.Profiles.professorDirectory;
import Business.Profiles.studentDirectory;
import Business.course;
import Business.signUpJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author niyatiashar
 */
public class FacultyManageCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageCourseJPanel
     */
    private JPanel UserProcessContainer;
    private studentDirectory studentDirectory;
    private professorDirectory professorDirectory;
    private course course;
    private CourseCatalog CourseCatalog;

    public FacultyManageCoursesJPanel(JPanel UserProcessContainer, professorDirectory professorDirectory, studentDirectory studentDirectory) {
        initComponents();
       this.UserProcessContainer = UserProcessContainer;
       this.studentDirectory = studentDirectory;
       this.professorDirectory = professorDirectory;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcourseDetails = new javax.swing.JTable();
        lblmanageCourse = new javax.swing.JLabel();
        btnCreatCourse = new javax.swing.JButton();

        tblcourseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Course Number", "Term Offered", "Day", "Time"
            }
        ));
        jScrollPane1.setViewportView(tblcourseDetails);

        lblmanageCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblmanageCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmanageCourse.setText("Manage Courses");

        btnCreatCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnCreatCourse.setText("Create Course");
        btnCreatCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmanageCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreatCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblmanageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnCreatCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatCourseActionPerformed
        // TODO add your handling code here:

        FacultyCreateCourseJPanel facultycreatecoursejpanel = new FacultyCreateCourseJPanel(UserProcessContainer, professorDirectory, studentDirectory, course, CourseCatalog );
        UserProcessContainer.add("FacultyCreateCourseJPanel", facultycreatecoursejpanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        System.out.println("Switching to SignUpJPanel");
        layout.next(UserProcessContainer);


    }//GEN-LAST:event_btnCreatCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatCourse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmanageCourse;
    private javax.swing.JTable tblcourseDetails;
    // End of variables declaration//GEN-END:variables
}
