/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

/**
 *
 * @author niyatiashar
 */
public class FacultyCreateCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyCreateCourseJPanel
     */
    public FacultyCreateCourseJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacultyCreateCourse = new javax.swing.JLabel();
        lblCreateCourse = new javax.swing.JLabel();
        txtCreateCourse = new javax.swing.JTextField();
        lblCourseNumber = new javax.swing.JLabel();
        txtCourseNumber = new javax.swing.JTextField();
        lblTerm = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        lblModeOfTeaching = new javax.swing.JLabel();
        txtModeOfTeaching = new javax.swing.JTextField();
        lblDay = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        lblFacultyCreateCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblFacultyCreateCourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultyCreateCourse.setText("Create Course");

        lblCreateCourse.setText("Create Course:");

        lblCourseNumber.setText("Course Number:");

        lblTerm.setText("Term:");

        lblModeOfTeaching.setText("Mode of Teaching:");

        lblDay.setText("Day:");

        lblTime.setText("Time:");

        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblFacultyCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTime)
                    .addComponent(lblModeOfTeaching)
                    .addComponent(lblTerm)
                    .addComponent(lblCourseNumber)
                    .addComponent(lblCreateCourse)
                    .addComponent(lblDay))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCreateCourse)
                        .addComponent(txtCourseNumber)
                        .addComponent(txtTerm)
                        .addComponent(txtModeOfTeaching)
                        .addComponent(txtDay)
                        .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblFacultyCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateCourse)
                    .addComponent(txtCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerm)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModeOfTeaching)
                    .addComponent(lblModeOfTeaching, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDay)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblCreateCourse;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblFacultyCreateCourse;
    private javax.swing.JLabel lblModeOfTeaching;
    private javax.swing.JLabel lblTerm;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtCourseNumber;
    private javax.swing.JTextField txtCreateCourse;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtModeOfTeaching;
    private javax.swing.JTextField txtTerm;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
