/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.CourseCatalog;
import Business.Profiles.professor;
import Business.Profiles.professorDirectory;
import Business.Profiles.student;
import Business.Profiles.studentDirectory;
import Business.course;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niyatiashar
 */
public class StudentRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form registrationJPanel
     */
    private course course;
    private professor professor;
    private studentDirectory studentDirectory;
    private CourseCatalog CourseCatalog;
    
    public StudentRegistrationJPanel(JPanel UserProcessContainer, professorDirectory professordirectory, studentDirectory studentdirectory) {
        initComponents();
        this.CourseCatalog= CourseCatalog;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblProfessor = new javax.swing.JLabel();
        txtProfessor = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseRegistration = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Registration");

        lblProfessor.setText("Professor Name:");

        lblCourseName.setText("Course Name:");

        lblLanguage.setText("Language:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");

        tblCourseRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Course Number", "Language", "Term", "Professor Name", "Day", "Time"
            }
        ));
        jScrollPane1.setViewportView(tblCourseRegistration);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnSearch)
                            .addGap(27, 27, 27)
                            .addComponent(btnClear))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblProfessor)
                                .addComponent(lblLanguage)
                                .addComponent(lblCourseName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProfessor)
                                .addComponent(txtCourseName)
                                .addComponent(txtLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessor)
                    .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLanguage)
                    .addComponent(lblLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnClear))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    Map<String, ArrayList<course>> mapOfCourse = CourseCatalog.createProfessorCourseMap(); // Make sure to retrieve or generate this data
    PopulateTable(mapOfCourse);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void PopulateTable( Map<String, ArrayList<course>> mapOfCourse) {
        DefaultTableModel dtm = (DefaultTableModel) tblCourseRegistration.getModel();
    dtm.setRowCount(0);

    String professorName = txtProfessor.getText().trim();
    String courseName = txtCourseName.getText().trim();
    String language = txtLanguage.getText().trim();

    // Get the professor-course mapping from the HashMap
    //Map<String, ArrayList<course>> mapOfCourse = createProfessorCourseMap();
    
    for (String profName : mapOfCourse.keySet()) {
            ArrayList<course> professorCourses = mapOfCourse.get(profName);
            for (course course : professorCourses) {
                if (courseMatchesCriteria(course, professorName, courseName, language)) {
                    Object[] row = new Object[7];
                    row[0] = course.getCourseName();
                    row[1] = course.getCourseID();
                    row[2] = course.getLanguage();
                    row[3] = course.getTerm();
                    row[4] = course.getProfessorName();
                    row[5] = course.getCourseDay();
                    row[6] = course.getCourseTime();

                    dtm.addRow(row);
            }
        }
    }
    
    
    }
    
    private boolean courseMatchesCriteria(course course, String professorName, String courseName, String language) {
        if (!professorName.isEmpty() && !course.getProfessorName().equalsIgnoreCase(professorName)) {
            return false;
        }

        if (!courseName.isEmpty() && !course.getCourseName().equalsIgnoreCase(courseName)) {
            return false;
        }

        if (!language.isEmpty() && !course.getLanguage().equalsIgnoreCase(language)) {
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JTable tblCourseRegistration;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtProfessor;
    // End of variables declaration//GEN-END:variables
}
