/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;



import Business.Profiles.professorDirectory;
import Business.Profiles.studentDirectory;
import Business.loginJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author niyatiashar
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {
     /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */
    
    private studentDirectory studentdirectory;
    private professorDirectory professordirectory;
    private JPanel UserProcessContainer;
    public StudentWorkAreaJPanel( JPanel UserProcessContainer, studentDirectory studentdirectory, professorDirectory professordirectory) {

        //business = b;
       // this.CardSequencePanel = clp;
//       / student = spp;
        initComponents();

   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStudentCourseWork = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        btnStudentManageProfile = new javax.swing.JButton();
        btnStudentTranscript = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Student Portal");

        btnStudentCourseWork.setText("Course Work");
        btnStudentCourseWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCourseWorkActionPerformed(evt);
            }
        });

        btnStudentRegistration.setText("Registration");
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        btnStudentManageProfile.setText("Manage Profile");
        btnStudentManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManageProfileActionPerformed(evt);
            }
        });

        btnStudentTranscript.setText("Transcript");
        btnStudentTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentTranscriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStudentCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentManageProfile))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStudentTranscript, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStudentRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnStudentCourseWork, btnStudentManageProfile, btnStudentTranscript});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentRegistration))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentManageProfile)
                    .addComponent(btnStudentTranscript))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnStudentCourseWork, btnStudentManageProfile, btnStudentRegistration, btnStudentTranscript});

    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        StudentRegistrationJPanel studentregistrationjpanel = new StudentRegistrationJPanel(UserProcessContainer, professordirectory, studentdirectory );
        UserProcessContainer.add("StudentRegistrationJPanel", studentregistrationjpanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        System.out.println("Switching to StudentRegistrationJPanel");
        layout.next(UserProcessContainer);

    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnStudentCourseWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCourseWorkActionPerformed
        // TODO add your handling code here:
        StudentCourseWorkJPanel studentcourseworkjpanel = new StudentCourseWorkJPanel(UserProcessContainer, professordirectory, studentdirectory );
        UserProcessContainer.add("StudentCourseWorkJPanel", studentcourseworkjpanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        System.out.println("Switching to StudentCourseWorkJPanel");
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnStudentCourseWorkActionPerformed

    private void btnStudentManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManageProfileActionPerformed
        // TODO add your handling code here:
        StudentManageProfileJPanel studentmanageprofilejpanel = new StudentManageProfileJPanel(UserProcessContainer, professordirectory, studentdirectory );
        UserProcessContainer.add("StudentManageProfileJPanel", studentmanageprofilejpanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        System.out.println("Switching to StudentManageProfileJPanel");
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnStudentManageProfileActionPerformed

    private void btnStudentTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentTranscriptActionPerformed
        // TODO add your handling code here:
        StudentTranscriptJPanel studenttranscriptjpanel = new StudentTranscriptJPanel(UserProcessContainer, professordirectory, studentdirectory );
        UserProcessContainer.add("StudentTranscriptJPanel", studenttranscriptjpanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        System.out.println("Switching to StudentTranscriptJPanel");
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_btnStudentTranscriptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentCourseWork;
    private javax.swing.JButton btnStudentManageProfile;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JButton btnStudentTranscript;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
