/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business;

import Business.Profiles.professor;
import Business.Profiles.professorDirectory;
import Business.Profiles.student;
import Business.Profiles.studentDirectory;

import UniversalPackageAuthority.UniversalCertificationAuthorityJPanel;
import UserInterface.WorkAreas.AdminRole.AdminRoleWorkAreaJPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author dshev
 */
public class loginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form loginJPanel
     */
    private JPanel UserProcessContainer;
    private professorDirectory professordirectory;
    private studentDirectory studentdirectory;
    private course course;
    private CourseCatalog CourseCatalog;

    public loginJPanel(JPanel UserProcessContainer, professorDirectory professordirectory, studentDirectory studentdirectory, course course, CourseCatalog CourseCatalog ) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.professordirectory = professordirectory;
        this.studentdirectory = studentdirectory;
        this.course = course;
        this.CourseCatalog = CourseCatalog;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        lblUserName.setText("User Name :");

        jLabel1.setText("Password :");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String userName = txtUserName.getText();
        char[] passwordChars = txtPassword.getPassword();
        String pwd = new String(passwordChars);

        if (userName.equals("admin") && pwd.equals("Admin@1234")) {
            // Admin login
            AdminRoleWorkAreaJPanel adminworkareapanel = new AdminRoleWorkAreaJPanel(UserProcessContainer, professordirectory, studentdirectory);
            UserProcessContainer.add("AdminRoleWorkAreaJPanel", adminworkareapanel);
            CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
            layout.next(UserProcessContainer);
            
            System.out.println("Went into admin");
        } 
        else if (userName.isEmpty() || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Some fields are empty");
             System.out.println("Went into select");
        } 
        else if (userName.equals("athority") && pwd.equals("Authority@1234")) {

            UniversalCertificationAuthorityJPanel universalauthority = new UniversalCertificationAuthorityJPanel(UserProcessContainer, professordirectory, studentdirectory);
            UserProcessContainer.add("UniversalCertificationAuthorityJPanel", universalauthority);
            CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
            layout.next(UserProcessContainer); 
             System.out.println("Went into authority");
        }
        else {
            boolean found = false;

            ArrayList<student> studList = studentdirectory.getstudentList();
            for (student stud : studList) {
                if (userName.equals(stud.getStudUserName())) {
                    
                    StudentWorkAreaJPanel studentworkareajpanel = new StudentWorkAreaJPanel(UserProcessContainer, studentdirectory, professordirectory);
                    UserProcessContainer.add("StudentWorkAreaJPanel", studentworkareajpanel);
                    CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
                    layout.next(UserProcessContainer);
                    found = true;
                     System.out.println("Went into student");
                    break; // Exit the loop as the user is found
                    
                }
            }

            if (!found) {
                // Check professors only if the user is not found among students
                ArrayList<professor> profList = professordirectory.getProfessorList();
                for (professor prof : profList) {
                    if (userName.equals(prof.getProfUserName())) {
                        // Professor login
                        // Redirect to Professor panel      
                        FacultyWorkAreaJPanel facultyworkareajpanel = new FacultyWorkAreaJPanel(UserProcessContainer, studentdirectory, professordirectory, course, CourseCatalog);
                        
                       // course course, CourseCatalog CourseCatalog
                        UserProcessContainer.add("FacultyWorkAreaJPanel", facultyworkareajpanel);
                        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
                        layout.next(UserProcessContainer);
                         System.out.println("Went into professor");
                        found = true;
                        // You need to implement ProfessorWorkAreaJPanel or handle professor login accordingly.
                        break;
                    }
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(btnLogin, "Invalid username or password");
                 System.out.println("Went into Invalid");
            }
        }


    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
